org: lmiranda
app: notes
service: notes-api
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

functions:
  authorizer:
    handler: authorizer.handler

  createNote:
    handler: handler.createNote
    environment:
      NOTES_TABLE_NAME: !Ref zmmttNotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt zmmttNotesTable.Arn
    events:
      - http: 
          method: post
          path: notes
          authorizer: authorizer

  updateNote:
    handler: handler.updateNote
    environment:
      NOTES_TABLE_NAME: !Ref zmmttNotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt zmmttNotesTable.Arn
    events:
      - http: 
          method: put
          path: notes/{idNota}
          authorizer: authorizer

  deleteNote:
    handler: handler.deleteNote
    environment:
      NOTES_TABLE_NAME: !Ref zmmttNotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt zmmttNotesTable.Arn
    events:
      - http: 
          method: delete 
          path: notes/{idNota}  
          authorizer: authorizer

  getAllNotes:
    handler: handler.getAllNotes
    environment:
      NOTES_TABLE_NAME: !Ref zmmttNotesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt zmmttNotesTable.Arn
    events:
      - http: 
          method: get
          path: notes
          authorizer: authorizer

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    zmmttNotesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: zmmttNotesTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: notesID
            AttributeType: S
        KeySchema:
          - AttributeName: notesID
            KeyType: HASH